import React, { useState } from 'react';
import { ButtonContainer } from '../../../theme/Buttons';
import styles from './styles.module.scss';
import { LinkButton } from '/src/theme/Buttons';
import Link from '@docusaurus/Link';

export default function Details() {
  return (
    <div className={styles.bgCol}>
      <div className="container">
        <div className={styles.header}>
          <h2>Generative Feedback Loops with Weaviate</h2>
          <p>
            Retrieving information from the Weaviate Vector Database to prompt
            Weaviate’s generative module and then vectorizing and saving these
            generations back into the database! Now you can semantically search
            through the generated content, as well as add symbolic metadata
            about it.
          </p>
        </div>
        <div className={styles.typeContainer}>
          <div className={styles.typeBox}>
            <div className={styles.typeIcon}>
              <div className={styles.homeIcon}></div>
              <h2>Supplement your existing data</h2>
            </div>
            <div className={styles.typeText}>
              <p>
                Enrich your data set by saving answers generated by LLMs back
                into your database.
              </p>
            </div>
          </div>
          <div className={styles.typeBox}>
            <div className={styles.typeIcon}>
              <div className={`${styles.homeIcon} ${styles.search}`}></div>
              <h2>Reduce tedious, manual work</h2>
            </div>
            <div className={styles.typeText}>
              <p>
                Automate the cleaning and organizing of existing data, such as
                adding tags or labels.
              </p>
            </div>
          </div>
          <div className={styles.typeBox}>
            <div className={styles.typeIcon}>
              <div className={`${styles.homeIcon} ${styles.scale}`}></div>
              <h2>Gain the advantage of speed</h2>
            </div>
            <div className={styles.typeText}>
              <p>
                Produce business outcomes faster with a clearer picture of your
                data.
              </p>
            </div>
          </div>
        </div>
        <div className={styles.serviceBox}>
          <div className={styles.serviceText}>
            <div className={styles.serviceIcon}></div>
            <span>Case Study</span>
            <h2>Transforming Customer Service with Generative AI</h2>

            <p>
              Learn how Neople Assistants transform customer service with
              Weaviate
            </p>
          </div>

          <div className={styles.serviceImage}></div>
        </div>
      </div>
    </div>
  );
}
