/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'weaviate'
    },
    {
      type: 'html',
      value: '<div class="separator"></div>',
    },
    {
      type: 'link',
      label: 'Weaviate Cloud Services docs',
      href: '/developers/wcs',
    },
    {
      type: 'link',
      label: 'Contributor guide',
      href: '/developers/contributor-guide',
    },
  ],
  academySidebar: [
    {
      type: 'autogenerated',
      dirName: 'academy'
    },
  ],
  contributorSidebar: [
    {
      type: 'autogenerated',
      dirName: 'contributor-guide'
    },
  ],
  wcsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'wcs'
    },
    {
      type: 'html',
      value: '<div class="separator"></div>',
    },
    {
      type: 'link',
      label: 'Weaviate docs',
      href: '/developers/weaviate',
    },
    {
      type: 'link',
      label: 'Contributor guide',
      href: '/developers/contributor-guide',
    },
  ],
};

module.exports = sidebars;
