blank_issues_enabled: true
contact_links:
  - name: Community Slack
    url: https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw
    about: Chat with the community about any issues, questions, or feedback
